pipeline{
	agent any
	stages {
		stage('Compile Stage'){
			steps{
				withMaven(maven : 'maven_3_5_0'){
					cmd 'mvn clean compile'
				}
			}
		}
		
		stage('Test Stage'){
			steps{
				withMaven(maven : 'maven_3_5_0'){
					cmd 'mvn test'
				}
			}
		}
		
		stage('Deploy Stage'){
			steps{
				withMaven(maven : 'maven_3_5_0'){
					cmd 'mvn deploy'
				}
			}
		}
	}
}